[tool.poetry]
name = "jf1uids"
version = "0.1.0"
description = "conservative, differentiable, radial 1d fluid solver with astrophysical modules"
authors = ["Leonard Storcks <leonard.storcks@stud.uni-heidelberg.de>"]
readme = "README.md"
packages = [{include = "jf1uids"}]

[tool.poetry.dependencies]
python = "^3.11"
optax = "^0.2.3"
jax = "^0.4.31"
scipy = "^1.14.1"
astropy = "^6.1.3"
numpy = "^2.1.1"
equinox = "^0.11.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"