blast_creation:
  randomizer_1: [0.5, 1.5]
  randomizer_2: [0.5, 1.5]
  randomizer_3: [0.5, 1.5]

training:
  hr_res : 64
  downscaling_factor : 2
  epochs : 2
  hidden_channels: 16
  n_look_behind : 6