defaults:
  - _self_
  - training: variable_losses
  - data: turbulence
  - models: fno

experiment:
  name: "turbulence_force_corrector"

data:
  debug: ${training.debug}

hydra:
  job:
    chdir: true
  run:
    dir: experiments/${experiment.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: experiments/${experiment.name}/multirun/${now:%Y-%m-%d}_${now:%H-%M-%S}_nlook_${training.n_look_behind}