defaults:
  - _self_
  - training: basic_training
  - data: data
  - models: cnn

experiment:
  name: "experiment_1"

data:
  debug: ${training.debug}

hydra:
  job:
    chdir: true
  run:
    dir: experiments/${experiment.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${training.n_look_behind}
  sweep:
    dir: experiments/${experiment.name}/multirun/${now:%Y-%m-%d}_${now:%H-%M-%S}_nlook_${training.n_look_behind}